### ISSUE TITLE
Clearing uncommitted changes

### ISSUE THREAD

**Issue by bsall** [gregoryyoung/m-r#2]
Hi, thanks for this nice work.
I have a question : when are the uncommited changes of the aggregate cleared ?

**Comment by marco-fiset** [comment]
With the web application being fully decoupled from the domain, uncommitted changes should definitely be cleared upon saving the aggregate. Your domain does not want to assume which context it's being used in.

**Comment by beachwalker** [comment]
Maybe the repository should do it this way:

        public void Save(AggregateRoot aggregate, int expectedVersion)
        {
            this.storage.SaveEvents(aggregate.Id, aggregate.GetUncommittedChanges(), expectedVersion);

            aggregate.MarkChangesAsCommitted();
        }
