### ISSUE TITLE
Use ReflectionMagic and get rid of InfrastructureCrap.DontBotherReadingItsNotImportant.cs

### ISSUE THREAD

**Issue by JohannesHoppe** [gregoryyoung/m-r#26]
see the evil [`this.AsDynamic()`](https://github.com/gregoryyoung/m-r/blob/31d315faf272182d7567a038bbe832a73b879737/SimpleCQRS/Domain.cs#L93) which is used to call one of the `Apply()` methods of the aggregate root (in our case [`InventoryItem.Apply()`](https://github.com/gregoryyoung/m-r/blob/31d315faf272182d7567a038bbe832a73b879737/SimpleCQRS/Domain.cs#L11))

@davidebbo (author of the referenced [blogpost](http://blogs.msdn.com/b/davidebb/archive/2010/01/18/use-c-4-0-dynamic-to-drastically-simplify-your-private-reflection-code.aspx)) developed this to a full nuget package:
https://github.com/davidebbo/ReflectionMagic
we should use this and get rid of `InfrastructureCrap.DontBotherReadingItsNotImportant.cs` :smile:

**Comment by gregoryyoung** [comment]
This is not an attempt at creating a framework you can reuse, it is an example of how things can work.

**Comment by JohannesHoppe** [comment]
I see! ;-)
