### ISSUE TITLE
CQRS and CRUD misconception

### ISSUE THREAD

**Issue by lecoque** [gregoryyoung/m-r#28]
There are many articles and videos like "CQRS vs CRUD". They're not even the same things. Because you can use CQRS with CRUD (for example, CreateCommand, UpdateCommand, DeleteCommand) and mostly all applications are CRUD.  Can you clarify?

Is implementing CRUD using CQRS misusing CQRS?

Is CQRS suitable for implementing REST/resource-based APIs with CRUD mental model, or it's a better fit for RPC APIs?

How do you use CQRS with DDD, how do you map to domain models? Do you map directly from your commands to domain models? Or do you use commands just as DTO holders? see https://stackoverflow.com/questions/50908260/cqrs-with-mediatr-and-re-usability-of-commands

**Comment by gregoryyoung** [comment]
UpdateEntity Customer { id : 44465, active : false }

is very different than

DeactivateCustomer {id 44465 }

**Comment by lecoque** [comment]
@gregoryyoung but when you create REST API it always looks like the first example.

**Comment by gregoryyoung** [comment]
<account>
    <account_number>12345</account_number>
    <balance currency="usd">100.00</balance>
    <link rel="deposit" href="/account/12345/deposit" />
    <link rel="withdraw" href="/account/12345/withdraw" />
    <link rel="transfer" href="/account/12345/transfer" />
    <link rel="close" href="/account/12345/close" />
</account>

as example.

**Comment by lecoque** [comment]
CQRS/CQS doesn't say anything about the single responsibility of a command. It tells to just isolate write methods from read methods.

**Comment by rganz** [comment]
When I started with CQRS I struggled with the same "mismatch", what helped me is this:
- leave the "update resources" thinking and think more task-oriented. This may also mean changing the user interface so that users does not see forms of fields and check boxes with a single "update" button, but multiple task buttons like "Deactivate user". There are several articles about task oriented UIs like this: https://cqrs.wordpress.com/documents/task-based-ui/
- see also: REST without PUT https://www.thoughtworks.com/insights/blog/rest-api-design-resource-modeling

**Comment by gregoryyoung** [comment]
@rganz at first I thought that was to me and was going to be forced to point out the irony that I wrote the first article :P

**Comment by lecoque** [comment]
@rganz Yeah there's a confusion when talking about CQRS in Task-oriented UIs vs CRUD oriented UIs. The definition of the pattern looks different for both. For example, the definition for CRUD oriented UIs presents CQRS as:

**CustomerWriteService**
```
void MakeCustomerPreferred(CustomerId)
void ChangeCustomerLocale(CustomerId, NewLocale)
void CreateCustomer(Customer)
void EditCustomerDetails(CustomerDetails)
```
**CustomerReadService**
```
Customer GetCustomer(CustomerId)
CustomerSet GetCustomersWithName(Name)
CustomerSet GetPreferredCustomers()
```

While for Task oriented UIs the definition for Command changes:

> Commands
The method through which the Application Server will be told what to do is through the use of a
Command. A command is a simple object with a name of an operation and the data required to perform
that operation. Many think of Commands as being Serializable Method Calls. Listing 1 includes the code
of a basic command.

From: https://cqrs.files.wordpress.com/2010/11/cqrs_documents.pdf

It seems like it applies differently in different usage contexts.

**Comment by gregoryyoung** [comment]
The definitions for me are the same, how do you find them different?

**Comment by lecoque** [comment]
@gregoryyoung There are no "SomeActionCommand" classes in your example of CQRS with CustomerWriteService and CustomerReadService and microsoft definition describes commands as operations not data models/structures of data.

**Comment by gregoryyoung** [comment]
My slide for CQRS does not normally have reads going through the domain so I am a bit confused.

![image](https://user-images.githubusercontent.com/381274/41542995-3fdbca5e-7340-11e8-8b2a-b3587790dda9.png)

**Comment by lecoque** [comment]
One definition says that

> A command is a simple object with a name of an operation and the data required to perform

Other definition says that:

> CQRS is a pattern that segregates the operations that read data (queries) from the operations that update data (commands) by using separate interfaces

One definition speaks of a command as of a "simple object". The second definition speaks of a command as operation that update data.

The original definition of CQS talks about commands as of methods, not objects.

**Comment by gregoryyoung** [comment]
CQRS can be applied to methods or messages. To be fair the difference is rather not worth discussing as some languages use messages to implement method calls :)

**Comment by lecoque** [comment]
@gregoryyoung I think it's worth discussing because "Command" gets a different meaning when applied to messages.

**Comment by gregoryyoung** [comment]
Like what SimpleCQRS does? #TrollLOLLOL :P

https://github.com/gregoryyoung/m-r/blob/master/SimpleCQRS/Commands.cs

**Comment by lecoque** [comment]
@gregoryyoung Can't this duplication be a bit simplified?

https://github.com/gregoryyoung/m-r/blob/31d315faf272182d7567a038bbe832a73b879737/SimpleCQRS/Commands.cs#L43-L46

https://github.com/gregoryyoung/m-r/blob/31d315faf272182d7567a038bbe832a73b879737/SimpleCQRS/Commands.cs#L55-L58

**Comment by gregoryyoung** [comment]
Could be but you probably don't want to. They are defining schema. What happens when you have 3 levels of inheritance etc and need to change something higher up? How much time did you save through you reuse?

**Comment by lecoque** [comment]
@gregoryyoung I have CRUD based UI does it make sense to apply CQRS?

**Comment by gregoryyoung** [comment]
Not usually though it can. Normally you are more interested in behaviours, why something happens is often important. If you just need CRUD why not just maintain a SQL transaction file?

**Comment by gregoryyoung** [comment]
That was my original point. Often no. I have discussed this a lot in talks there are simpler ways of reaching the same goal such as an audit table on updates. I am not trying to put you off the idea (it has benefits) but often they will not be realized IME
