### ISSUE TITLE
InventoryItemRenamed: Can't for the life of me see where this is being handled

### ISSUE THREAD

**Issue by wil-den** [gregoryyoung/m-r#38]
I have been having a look at this implementation and I believe I understand what is happening. However for the above named event, I can't figure where the change is being applied. It is super bugging me that i can't see it and would appreciate you helping me scratch this itch.
The Aggregateroot does not having a matching overloaded method. When debugging in your `PrivateReflectionDynamicObject` i see nothing but MissingMethodExceptions and the call eventually returns with no `Apply` method being called.
I appreciate you wrote this code a long time ago. But I would sincerely appreciate any pointers here. Might help me sleep a little easier tonight :)

**Comment by Narvalex** [comment]
It appears that the `AggregateRoot` does not consider the name significant, as it does not check if the new name differs from the previous one. However, the ReadModel does take the name into account, as demonstrated below:
https://github.com/gregoryyoung/m-r/blob/b6a7b67961f3157038499335f1868795e2f6d33a/SimpleCQRS/ReadModel.cs#L49

**Comment by ghost** [comment]
Thank you :)
