### ISSUE TITLE
Why use DelegateAdjuster?

### ISSUE THREAD

**Issue by payman81** [gregoryyoung/m-r#8]
Hi 
Why do you need to use DelegateAdjuster below
https://github.com/gregoryyoung/m-r/blob/master/SimpleCQRS/FakeBus.cs#L21

Why not use below to explicitly cast the parameter?
 handlers.Add((x => handler((T)x)));

Thanks

Payman

**Comment by gregoryyoung** [comment]
You can (and I do in a later version of code)

On Tue, Apr 7, 2015 at 7:54 PM, payman81 <notifications@github.com> wrote:

> Hi
> Why do you need to use DelegateAdjuster below
> https://github.com/gregoryyoung/m-r/blob/master/SimpleCQRS/FakeBus.cs#L21
>
> Why not use below to explicitly cast the parameter?
> handlers.Add((x => handler((T)x)));
>
> Thanks
>
> Payman
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gregoryyoung/m-r/issues/8>.
>



-- 
Studying for the Turing test
